<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'name' => 'sugar',
                'slug' => 'sugar',
                'photos'=> 'uploads/products/1.jpg|uploads/products/2.jpg|uploads/products/3.jpg|uploads/products/4.jpg',
                'thumbnail' => 'uploads/products/2.jpg',
                'summary' => 'The iPhone 12 Pro Max is a smartphone by Apple .',
                'description' => 'The iPhone 12 Pro Max is a smartphone by Apple that was released in October 2020. The phone runs on the iOS 14.0.1 operating system. The iPhone 12 Pro Max has a 6.7-inch Super Retina XDR OLED display with a resolution of 1284x2778 pixels at a pixel density of 458 pixels per inch (ppi). The Apple A14 Bionic chipset is paired with 6GB of RAM and 128GB/256GB/512GB of internal storage. As far as the cameras are concerned, the iPhone 12 Pro Max on the rear packs a 12-megapixel primary camera with an f/1.6 aperture and a pixel size of 1.4-micron and a second 12-megapixel camera with an f/2.4 aperture and a pixel size of 1.0-micron. The rear camera setup has autofocus. It sports a 12-megapixel camera on the front for selfies, with an f/2.2 aperture and a pixel size of 1.22-micron.',
                'price' => 1099,
                'discount' => 10,
                'discount_type' => 'percent',
                'discount_start' => '2021-02-01',
                'discount_end' => '2021-02-28',
                'sku' => 'sku-001',
                'barcode' => 'barcode-001',
                'stock' => 100,
                'stock_alert' => 10,
                'weight' => '1.5kg',
                'meta_title' => 'Apple iPhone 12 Pro Max',
                'meta_description' => 'The iPhone 12 Pro Max is a smartphone by Apple .',
                'meta_keywords' => 'Apple, iPhone, 12, Pro, Max',
                'status' => 'active',
                'featured' => 'yes',
                'trending' => 'yes',
                'best_rated' => 'yes',
                'hot_new' => 'yes',
                'buyone_getone' => 'yes',
                'special_offer' => 'yes',
                'special_deal' => 'yes',
                'vat' => 10,
                'tax' => 10,
                'free_shipping' => 'yes',
                'product_video_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'product_audio_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'product_file_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'category_id' => 1,
                'brand_id' => 1,
                'user_id' => 1,
                'color_id' => 1,
            ],
            [
                'name' => 'salt',
                'slug' => 'salt-slug',
                'photos'=> 'uploads/products/3.jpg|uploads/products/4.jpg|uploads/products/5.jpg|uploads/products/6.jpg',
                'thumbnail' => 'uploads/products/2.jpg',
                'summary' => 'The iPhone 12 Pro Max is a smartphone by Apple .',
                'description' => 'The iPhone 12 Pro Max is a smartphone by Apple that was released in October 2020. The phone runs on the iOS 14.0.1 operating system. The iPhone 12 Pro Max has a 6.7-inch Super Retina XDR OLED display with a resolution of 1284x2778 pixels at a pixel density of 458 pixels per inch (ppi). The Apple A14 Bionic chipset is paired with 6GB of RAM and 128GB/256GB/512GB of internal storage. As far as the cameras are concerned, the iPhone 12 Pro Max on the rear packs a 12-megapixel primary camera with an f/1.6 aperture and a pixel size of 1.4-micron and a second 12-megapixel camera with an f/2.4 aperture and a pixel size of 1.0-micron. The rear camera setup has autofocus. It sports a 12-megapixel camera on the front for selfies, with an f/2.2 aperture and a pixel size of 1.22-micron.',
                'price' => 1099,
                'discount' => 10,
                'discount_type' => 'percent',
                'discount_start' => '2021-02-01',
                'discount_end' => '2021-02-28',
                'sku' => 'sku-001',
                'barcode' => 'barcode-001',
                'stock' => 100,
                'stock_alert' => 10,
                'weight' => '1.5kg',
                'meta_title' => 'Apple iPhone 12 Pro Max',
                'meta_description' => 'The iPhone 12 Pro Max is a smartphone by Apple .',
                'meta_keywords' => 'Apple, iPhone, 12, Pro, Max',
                'status' => 'active',
                'featured' => 'yes',
                'trending' => 'yes',
                'best_rated'    => 'yes',
                'hot_new' => 'yes',
                'buyone_getone' => 'yes',
                'special_offer' => 'yes',
                'special_deal' => 'yes',
                'vat' => 10,
                'tax' => 10,
                'free_shipping' => 'yes',
                'product_video_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'product_audio_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'product_file_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'category_id' => 1,
                'brand_id' => 1,
                'user_id' => 1,
                'color_id' => 1,
            ],
            [
                'name' => 'Tomato',
                'slug' => 'tomato-slug',
                'photos'=> 'uploads/products/3.jpg|uploads/products/4.jpg|uploads/products/5.jpg|uploads/products/6.jpg',
                'thumbnail' => 'uploads/products/3.jpg',
                'summary' => 'Tomato Max is a smartphone by Apple .',
                'description' => 'The iPhone 12 Pro Max is a smartphone by Apple that was released in October 2020. The phone runs on the iOS 14.0.1 operating system. The iPhone 12 Pro Max has a 6.7-inch Super Retina XDR OLED display with a resolution of 1284x2778 pixels at a pixel density of 458 pixels per inch (ppi). The Apple A14 Bionic chipset is paired with 6GB of RAM and 128GB/256GB/512GB of internal storage. As far as the cameras are concerned, the iPhone 12 Pro Max on the rear packs a 12-megapixel primary camera with an f/1.6 aperture and a pixel size of 1.4-micron and a second 12-megapixel camera with an f/2.4 aperture and a pixel size of 1.0-micron. The rear camera setup has autofocus. It sports a 12-megapixel camera on the front for selfies, with an f/2.2 aperture and a pixel size of 1.22-micron.',
                'price' => 203,
                'discount' => 10,
                'discount_type' => 'percent',
                'discount_start' => '2021-02-01',
                'discount_end' => '2021-02-28',
                'sku' => 'sku-001',
                'barcode' => 'barcode-001',
                'stock' => 400,
                'stock_alert' => 10,
                'weight' => '1.9kg',
                'meta_title' => 'tomato meta title',
                'meta_description' => 'The iPhone 12 Pro Max is a smartphone by Apple .',
                'meta_keywords' => 'Apple, iPhone, 12, Pro, Max',
                'status' => 'active',
                'featured' => 'yes',
                'trending' => 'yes',
                'best_rated'    => 'yes',
                'hot_new' => 'yes',
                'buyone_getone' => 'yes',
                'special_offer' => 'yes',
                'special_deal' => 'yes',
                'vat' => 10,
                'tax' => 10,
                'free_shipping' => 'yes',
                'product_video_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'product_audio_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'product_file_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'category_id' => 3,
                'brand_id' => 4,
                'user_id' => 1,
                'color_id' => 7,
            ],
            [
                'name' => 'Rice vat',
                'slug' => 'rice-vat',
                'photos'=> 'uploads/products/5.jpg|uploads/products/6.jpg|uploads/products/7.jpg|uploads/products/8.jpg',
                'thumbnail' => 'uploads/products/5.jpg',
                'summary' => 'Rice  Max is a smartphone by Apple .',
                'description' => 'The RIce Pro Max is a smartphone by Apple that was released in October 2020. The phone runs on the iOS 14.0.1 operating system. The iPhone 12 Pro Max has a 6.7-inch Super Retina XDR OLED display with a resolution of 1284x2778 pixels at a pixel density of 458 pixels per inch (ppi). The Apple A14 Bionic chipset is paired with 6GB of RAM and 128GB/256GB/512GB of internal storage. As far as the cameras are concerned, the iPhone 12 Pro Max on the rear packs a 12-megapixel primary camera with an f/1.6 aperture and a pixel size of 1.4-micron and a second 12-megapixel camera with an f/2.4 aperture and a pixel size of 1.0-micron. The rear camera setup has autofocus. It sports a 12-megapixel camera on the front for selfies, with an f/2.2 aperture and a pixel size of 1.22-micron.',
                'price' => 160,
                'discount' => 20,
                'discount_type' => 'percent',
                'discount_start' => '2021-02-01',
                'discount_end' => '2021-02-28',
                'sku' => 'sku-001',
                'barcode' => 'barcode-001',
                'stock' => 300,
                'stock_alert' => 10,
                'weight' => '1.2kg',
                'meta_title' => 'rice meta title',
                'meta_description' => 'The iPhone 12 Pro Max is a smartphone by Apple .',
                'meta_keywords' => 'Apple, iPhone, 12, Pro, Max',
                'status' => 'active',
                'featured' => 'yes',
                'trending' => 'yes',
                'best_rated'    => 'yes',
                'hot_new' => 'yes',
                'buyone_getone' => 'yes',
                'special_offer' => 'yes',
                'special_deal' => 'yes',
                'vat' => 10,
                'tax' => 10,
                'free_shipping' => 'yes',
                'product_video_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'product_audio_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'product_file_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'category_id' => 2,
                'brand_id' => 6,
                'user_id' => 1,
                'color_id' => 3,
            ],
            [
                'name' => 'domex soap',
                'slug' => 'domex-soap-1',
                'photos'=> 'uploads/products/6.jpg|uploads/products/7.jpg|uploads/products/8.jpg|uploads/products/9.jpg',
                'thumbnail' => 'uploads/products/6.jpg',
                'summary' => 'domex  Max is a smartphone by Apple .',
                'description' => 'The domex Pro Max is a smartphone by Apple that was released in October 2020. The phone runs on the iOS 14.0.1 operating system. The iPhone 12 Pro Max has a 6.7-inch Super Retina XDR OLED display with a resolution of 1284x2778 pixels at a pixel density of 458 pixels per inch (ppi). The Apple A14 Bionic chipset is paired with 6GB of RAM and 128GB/256GB/512GB of internal storage. As far as the cameras are concerned, the iPhone 12 Pro Max on the rear packs a 12-megapixel primary camera with an f/1.6 aperture and a pixel size of 1.4-micron and a second 12-megapixel camera with an f/2.4 aperture and a pixel size of 1.0-micron. The rear camera setup has autofocus. It sports a 12-megapixel camera on the front for selfies, with an f/2.2 aperture and a pixel size of 1.22-micron.',
                'price' => 300,
                'discount' => 40,
                'discount_type' => 'percent',
                'discount_start' => '2021-02-01',
                'discount_end' => '2021-02-28',
                'sku' => 'sku-001',
                'barcode' => 'barcode-001',
                'stock' => 300,
                'stock_alert' => 10,
                'weight' => '1.2kg',
                'meta_title' => 'rice meta title',
                'meta_description' => 'The iPhone 12 Pro Max is a smartphone by Apple .',
                'meta_keywords' => 'Apple, iPhone, 12, Pro, Max',
                'status' => 'active',
                'featured' => 'yes',
                'trending' => 'yes',
                'best_rated'    => 'yes',
                'hot_new' => 'yes',
                'buyone_getone' => 'yes',
                'special_offer' => 'yes',
                'special_deal' => 'yes',
                'vat' => 10,
                'tax' => 10,
                'free_shipping' => 'yes',
                'product_video_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'product_audio_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'product_file_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'category_id' => 2,
                'brand_id' => 6,
                'user_id' => 1,
                'color_id' => 3,
            ],
            [
                'name' => 'fesh soap',
                'slug' => 'domex-soap-2',
                'photos'=> 'uploads/products/6.jpg|uploads/products/7.jpg|uploads/products/8.jpg|uploads/products/9.jpg',
                'thumbnail' => 'uploads/products/6.jpg',
                'summary' => 'domex  Max is a smartphone by Apple .',
                'description' => 'The domex Pro Max is a smartphone by Apple that was released in October 2020. The phone runs on the iOS 14.0.1 operating system. The iPhone 12 Pro Max has a 6.7-inch Super Retina XDR OLED display with a resolution of 1284x2778 pixels at a pixel density of 458 pixels per inch (ppi). The Apple A14 Bionic chipset is paired with 6GB of RAM and 128GB/256GB/512GB of internal storage. As far as the cameras are concerned, the iPhone 12 Pro Max on the rear packs a 12-megapixel primary camera with an f/1.6 aperture and a pixel size of 1.4-micron and a second 12-megapixel camera with an f/2.4 aperture and a pixel size of 1.0-micron. The rear camera setup has autofocus. It sports a 12-megapixel camera on the front for selfies, with an f/2.2 aperture and a pixel size of 1.22-micron.',
                'price' => 300,
                'discount' => 40,
                'discount_type' => 'percent',
                'discount_start' => '2021-02-01',
                'discount_end' => '2021-02-28',
                'sku' => 'sku-001',
                'barcode' => 'barcode-001',
                'stock' => 300,
                'stock_alert' => 10,
                'weight' => '1.2kg',
                'meta_title' => 'rice meta title',
                'meta_description' => 'The iPhone 12 Pro Max is a smartphone by Apple .',
                'meta_keywords' => 'Apple, iPhone, 12, Pro, Max',
                'status' => 'active',
                'featured' => 'yes',
                'trending' => 'yes',
                'best_rated'    => 'yes',
                'hot_new' => 'yes',
                'buyone_getone' => 'yes',
                'special_offer' => 'yes',
                'special_deal' => 'yes',
                'vat' => 10,
                'tax' => 10,
                'free_shipping' => 'yes',
                'product_video_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'product_audio_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'product_file_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'category_id' => 2,
                'brand_id' => 6,
                'user_id' => 1,
                'color_id' => 3,
            ],

            [
                'name' => 'onion',
                'slug' => 'onion-soap-1',
                'photos'=> 'uploads/products/9.jpg|uploads/products/4.jpg|uploads/products/1.jpg|uploads/products/9.jpg',
                'thumbnail' => 'uploads/products/7.jpg',
                'summary' => 'domex  Max is a smartphone by Apple .',
                'description' => 'The domex Pro Max is a smartphone by Apple that was released in October 2020. The phone runs on the iOS 14.0.1 operating system. The iPhone 12 Pro Max has a 6.7-inch Super Retina XDR OLED display with a resolution of 1284x2778 pixels at a pixel density of 458 pixels per inch (ppi). The Apple A14 Bionic chipset is paired with 6GB of RAM and 128GB/256GB/512GB of internal storage. As far as the cameras are concerned, the iPhone 12 Pro Max on the rear packs a 12-megapixel primary camera with an f/1.6 aperture and a pixel size of 1.4-micron and a second 12-megapixel camera with an f/2.4 aperture and a pixel size of 1.0-micron. The rear camera setup has autofocus. It sports a 12-megapixel camera on the front for selfies, with an f/2.2 aperture and a pixel size of 1.22-micron.',
                'price' => 600,
                'discount' =>70,
                'discount_type' => 'percent',
                'discount_start' => '2021-02-01',
                'discount_end' => '2021-02-28',
                'sku' => 'sku-001',
                'barcode' => 'barcode-001',
                'stock' => 300,
                'stock_alert' => 10,
                'weight' => '1.2kg',
                'meta_title' => 'rice meta title',
                'meta_description' => 'The iPhone 12 Pro Max is a smartphone by Apple .',
                'meta_keywords' => 'Apple, iPhone, 12, Pro, Max',
                'status' => 'active',
                'featured' => 'yes',
                'trending' => 'yes',
                'best_rated'    => 'yes',
                'hot_new' => 'yes',
                'buyone_getone' => 'yes',
                'special_offer' => 'yes',
                'special_deal' => 'yes',
                'vat' => 10,
                'tax' => 10,
                'free_shipping' => 'yes',
                'product_video_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'product_audio_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'product_file_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'category_id' => 2,
                'brand_id' => 6,
                'user_id' => 1,
                'color_id' => 3,
            ],
            [
                'name' => 'fesh soap',
                'slug' => 'domex-soap-4',
                'photos'=> 'uploads/products/6.jpg|uploads/products/7.jpg|uploads/products/8.jpg|uploads/products/9.jpg',
                'thumbnail' => 'uploads/products/6.jpg',
                'summary' => 'domex  Max is a smartphone by Apple .',
                'description' => 'The domex Pro Max is a smartphone by Apple that was released in October 2020. The phone runs on the iOS 14.0.1 operating system. The iPhone 12 Pro Max has a 6.7-inch Super Retina XDR OLED display with a resolution of 1284x2778 pixels at a pixel density of 458 pixels per inch (ppi). The Apple A14 Bionic chipset is paired with 6GB of RAM and 128GB/256GB/512GB of internal storage. As far as the cameras are concerned, the iPhone 12 Pro Max on the rear packs a 12-megapixel primary camera with an f/1.6 aperture and a pixel size of 1.4-micron and a second 12-megapixel camera with an f/2.4 aperture and a pixel size of 1.0-micron. The rear camera setup has autofocus. It sports a 12-megapixel camera on the front for selfies, with an f/2.2 aperture and a pixel size of 1.22-micron.',
                'price' => 300,
                'discount' => 40,
                'discount_type' => 'percent',
                'discount_start' => '2021-02-01',
                'discount_end' => '2021-02-28',
                'sku' => 'sku-001',
                'barcode' => 'barcode-001',
                'stock' => 300,
                'stock_alert' => 10,
                'weight' => '1.2kg',
                'meta_title' => 'rice meta title',
                'meta_description' => 'The iPhone 12 Pro Max is a smartphone by Apple .',
                'meta_keywords' => 'Apple, iPhone, 12, Pro, Max',
                'status' => 'active',
                'featured' => 'yes',
                'trending' => 'yes',
                'best_rated'    => 'yes',
                'hot_new' => 'yes',
                'buyone_getone' => 'yes',
                'special_offer' => 'yes',
                'special_deal' => 'yes',
                'vat' => 10,
                'tax' => 10,
                'free_shipping' => 'yes',
                'product_video_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'product_audio_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'product_file_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'category_id' => 2,
                'brand_id' => 6,
                'user_id' => 1,
                'color_id' => 3,
            ],

            [
                'name' => 'Washing Powser',
                'slug' => 'washing-powser',
                'photos'=> 'uploads/products/7.jpg|uploads/products/8.jpg|uploads/products/9.jpg|uploads/products/10.jpg',
                'thumbnail' => 'uploads/products/8.jpg',
                'summary' => 'washing powser  Max is a smartphone by Apple .',
                'description' => 'The domex Pro Max is a smartphone by Apple that was released in October 2020. The phone runs on the iOS 14.0.1 operating system. The iPhone 12 Pro Max has a 6.7-inch Super Retina XDR OLED display with a resolution of 1284x2778 pixels at a pixel density of 458 pixels per inch (ppi). The Apple A14 Bionic chipset is paired with 6GB of RAM and 128GB/256GB/512GB of internal storage. As far as the cameras are concerned, the iPhone 12 Pro Max on the rear packs a 12-megapixel primary camera with an f/1.6 aperture and a pixel size of 1.4-micron and a second 12-megapixel camera with an f/2.4 aperture and a pixel size of 1.0-micron. The rear camera setup has autofocus. It sports a 12-megapixel camera on the front for selfies, with an f/2.2 aperture and a pixel size of 1.22-micron.',
                'price' => 400,
                'discount' =>70,
                'discount_type' => 'percent',
                'discount_start' => '2021-02-01',
                'discount_end' => '2021-02-28',
                'sku' => 'sku-001',
                'barcode' => 'barcode-001',
                'stock' => 300,
                'stock_alert' => 10,
                'weight' => '1.2kg',
                'meta_title' => 'rice meta title',
                'meta_description' => 'The iPhone 12 Pro Max is a smartphone by Apple .',
                'meta_keywords' => 'Apple, iPhone, 12, Pro, Max',
                'status' => 'active',
                'featured' => 'yes',
                'trending' => 'yes',
                'best_rated'    => 'yes',
                'hot_new' => 'yes',
                'buyone_getone' => 'yes',
                'special_offer' => 'yes',
                'special_deal' => 'yes',
                'vat' => 10,
                'tax' => 10,
                'free_shipping' => 'yes',
                'product_video_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'product_audio_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'product_file_link' => 'https://www.youtube.com/watch?v=Q8TXgCzxEnw',
                'category_id' => 2,
                'brand_id' => 6,
                'user_id' => 1,
                'color_id' => 3,
            ],


        ]);
    }
}
